version: '2.1'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
    - "4200:4200"
    volumes:
    - .:/usr/src/front
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    volumes:
    - .:/usr/src/api
    command: nodemon -L index.js
